name: Akamai Purge on OSX
description: Purge Cache via Akamai Client API CLI on Mac OSX
inputs:
  command:
    description: The command from akamai purge command
    required: true
    default: invalidate
  type:
    description: Type of Ref, i.e. (tags, cpcode, url)
    required: false
    default: url
  ref:
    description: References tags, urls, etc
    required: true
  network:
    description: Network (production or staging)
    required: true
    default: production
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        echo -e "${EDGERC}" > ~/.edgerc
        brew install go
        brew install akamai
        akamai install purge
    - name: Purge
      shell: bash
      run: |
        akamai purge --edgerc ${HOME}/.edgerc --section ccu ${{ inputs.command }} ${{ inputs.network }} ${{ inputs.type }} ${{ inputs.ref }}
    - name: Cleanup
      if: ${{ always() }}
      shell: bash
      run: |
        rm -f ~/.edgerc
        brew uninstall akamai
        brew uninstall go
