name: Akamai Purge on OSX
description: Purge Cache via Akamai Client API CLI on Mac OSX
inputs:
  command:
    description: The command from akamai purge command
    required: true
    default: invalidate
  urls:
    description: urls
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        echo -e "${EDGERC}" > ~/.edgerc
        wget -O akamai https://github.com/akamai/cli/releases/download/v1.5.6/akamai-v1.5.6-linuxamd64
        chmod +x akamai
        ./akamai install purge
    - name: Purge
      shell: bash
      run: |
        MAX=50000
        urls="${{ inputs.urls }}"
        if [ ${#urls} -ge $MAX ]; then
          echo "Too many URLs. Splitting URLS in batches..."  
          indices=`echo $urls | grep -o -b " "`
          offset=0
          length=0
          for idx in $indices
          do
            end=${idx%:*}
            new_length=$((end - offset))
            if [ $new_length -ge $MAX ]; then
              echo "Batch from offset ${offset} of length ${length}"
              batch=${urls:$offset:$length}
              ./akamai purge --edgerc ~/.edgerc --section ccu ${{ inputs.command }} $batch
              offset=$((offset + length))
              length=$((end - offset))
            else
              length=$new_length
            fi
          done
          if [ $length -gt 0 ]; then
            length=$((${#urls} - offset + 1))
            echo "Last Batch from offset ${offset} of length ${length}"
            batch=${urls:$offset:$length}
            ./akamai purge --edgerc ~/.edgerc --section ccu ${{ inputs.command }} $batch
          fi
        else
          echo "Executing single Purge command..."  
          ./akamai purge --edgerc ~/.edgerc --section ccu ${{ inputs.command }} $urls
        fi
    - name: Cleanup
      if: ${{ always() }}
      shell: bash
      run: |
        rm -f ~/.edgerc
        ./akamai uninstall purge
        rm -f ./akamai
