inputs:
- name: sts4
- name: maven-cache
outputs:
- name: out
platform: linux
image_resource:
  type: registry-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
run:
  path: sts4/concourse/tasks/build-vsix.sh
