inputs:
- name: sts4
platform: linux
image_resource:
  type: docker-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
run:
  path: sts4/concourse/tasks/vsce-verify-token.sh
