name: 'Eclipse STS Distribution Build'
description: 'Takes eclipse profile string and build type to build Eclipse STS Distro'

inputs:
  eclipse_profile:
    description: Eclipse profile 'e428' etc
    required: true
  build_type:
    description: Build type such as 'snapshot', 'milestone' or 'release'
    required: true
    default: 'snapshot'

runs:
  using: "composite"
  steps:
    - name: Enforce https instead of http
      shell: bash
      run: ./nohttp.sh
    - name: Timestamp
      id: timestamp
      shell: bash
      run: echo "name=date::$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
    - name: Install GPG key
      shell: bash
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg.asc
        echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --import gpg.asc
    - name: Build Eclipse Distro
      shell: bash
      env:
        tools_s3_access_key: ${{ secrets.TOOLS_S3_ACCESS_KEY }}
        tools_s3_secret_key: ${{ secrets.TOOLS_S3_SECRET_KEY  }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        gpg_keyname: ${{ secrets.GPG_KEYID }}
      run: |
        cd eclipse-distribution
        mvn --batch-mode -U clean deploy -P${{ inputs.eclipse_profile }} -P${{ inputs.build_type }} -Pgitactions -Pgpg.sign -DbuildQualifier=${{ steps.timestamp.outputs.date }} -Dsigning.skip=true -Dmaven.repo.local=~/.m2/repository-signed -Dhttpclient.retry-max=20 -Dmaven.test.skip=true -Declipse.p2.mirrors=false -Dtycho.localArtifacts=ignore -Ds3service.https-only=true -Dp2.replaceQualifier=true -Dorg.eclipse.ecf.provider.filetransfer.httpclient.retrieve.readTimeout=1200000 -Dorg.eclipse.equinox.p2.transport.ecf.retry=5 -Dskip.eclipserun.proxies=false -Dskip.osx.signing=false  -Dskip.win.signing=false -Dskip.osx.notarizing=false -Dtycho.equinox.resolver.uses=true