name: Test Akamai Upload

on:
  workflow_dispatch:

jobs:
  akamai-upload:
    name: Upload to Akamai
    runs-on: ubuntu-latest
    steps:
      - name: Gen file and upload
        id: gen-upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLS_CLOUDGATE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_CLOUDGATE_SECRET_KEY  }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          file="upload-test.txt"
          echo 'Upload test file' > $file
          cat $file
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-role \
          --role-arn arn:aws:iam::${{ secrets.TOOLS_CLOUDGATE_ACCOUNT_ID }}:role/${{ secrets.TOOLS_CLOUDGATE_USER }} \
          --role-session-name gha-upload \
          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
          --output text))
          aws s3 mv ./$file s3://tools-spring-io/test-akamai/$file
