name: Akamai Purge Cache for Directory

on:
  workflow_call:
    inputs:
      s3-url:
        description: S3 URL
        required: true
        type: string
  workflow_dispatch:
    inputs:
      s3-url:
        description: S3 URL
        required: true
        type: string

jobs:

  clear-cache-s3-dir:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Cloudgate S3 Configuration
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          aws-access-key-id:  ${{ secrets.TOOLS_CLOUDGATE_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TOOLS_CLOUDGATE_SECRET_KEY  }}
          role-to-assume: arn:aws:iam::${{ secrets.TOOLS_CLOUDGATE_ACCOUNT_ID }}:role/${{ secrets.TOOLS_CLOUDGATE_USER }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-1
          role-duration-seconds: 900
          role-skip-session-tagging: true
      - name: Prepare URLs
        id: prepare-urls
        run: |
          urls=`aws s3 ls ${{ inputs.s3-url }} --recursive | awk '{$1=$2=$3=""; print $0}' | sed -e 's/^[ \t]*/https:\/\/cdn.spring.io\/spring-tools\//' | paste -sd' ' -`
          echo "urls=$urls" >> $GITHUB_OUTPUT
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          sparse-checkout: |
            .github
      - uses: ./.github/actions/akamai-purge-osx
        name: Invalidate Cache for URLs
        env:
          EDGERC: ${{ secrets.EDGERC }}
        with:
          command: invalidate
          urls: ${{ steps.prepare-urls.outputs.urls }}
