name: Build VSCode Extension

on:
  workflow_dispatch:
    inputs:
      extension-name:
        description: name of the extension, e.g. vscode-spring-cli
        required: true
        type: string
      dist:
        description: release, pre, snapshot
        required: false
        type: string
        default: snapshot

permissions:
  contents: write

jobs:
  build-vscode-extension:
    runs-on: ubuntu-latest
    name: Build VSCode Extension '${{ inputs.extension-name }}'
    steps:
      - name: Checkout vscode-extensions code and workflow scripts
        uses: actions/checkout@v4
      - name: Build .VSIX file
        id: build-vsix
        run: |
          ${{ github.workspace }}/.github/scripts/build-vscode-extension.sh ${{ inputs.extension-name }} ${{ inputs.dist }}
          ls ./vsix

