name: Debug Timestamp
on:
  workflow_dispatch:
jobs:

  eclipse-distro-build:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Timestamp
        id: timestamp
        run: echo "name=date::$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
      - name: Print timestamp
        run: |
          echo $(date +'%Y%m%dT%H%M%S')
          echo ${{ steps.timestamp.outputs.date }}
