name: Eclipse LS Extensions Snapshot

# configure manual trigger
on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - 'main'

jobs:

  eclipse-distro-build:
    runs-on: self-hosted
    labels:
      sts4-gha-01
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Enforce https instead of http
        run: ./nohttp.sh
      - name: Timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Build Language Servers JARs
        run: |
          cd headless-services
          xvfb-run mvn --batch-mode clean install -DskipTests
      - name: Install GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg.asc
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --import gpg.asc
      - name: Build Eclipse LS extensions
        env:
          tools_s3_access_key: ${{ secrets.TOOLS_S3_ACCESS_KEY }}
          tools_s3_secret_key: ${{ secrets.TOOLS_S3_SECRET_KEY  }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg_keyname: ${{ secrets.GPG_KEYID }}
          gpg_homedir: ${{ github.workspace }}
        run: |
          cd eclipse-language-servers
          xvfb-run mvn --batch-mode clean deploy -Pe427 -Psnapshot -Pgitactions -DbuildNumber=${{ steps.timestamp.outputs.timestamp }} -Dsigning.skip=true -Dhttpclient.retry-max=20 -Declipse.p2.mirrors=false -Ds3service.https-only=true -Dmaven.test.skip=true -Dtycho.localArtifacts=ignore