name: Release - Eclipse LS Extensions Build

concurrency:
  group: release-eclipse-ls-extensions
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  generate-sts4-ls-extensions-version:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    outputs:
      sts4-language-servers-version: ${{ steps.timestamp.outputs.date }}

  eclipse-ls-extension:
    needs: [ generate-sts4-ls-extensions-version ]
    uses: ./.github/workflows/eclipse-ls-extensions-build.yml
    with:
      eclipse_profile: 'e427'
      build_type: 'release'
      skip_tests: true
      sts4-language-servers-version: ${{ needs.generate-sts4-ls-extensions-version.outputs.sts4-language-servers-version }}
    secrets: inherit
