name: Release - Eclipse Build

concurrency:
  group: release-eclipse
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:

  eclipse-ls-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: ./.github/workflows/eclipse-ls-extensions-build.yml
        with:
          eclipse_profile: 'e427'
          build_type: 'release'
          skip_tests: true
          sts4-language-servers-version: ${{ steps.timestamp.outputs.date }}
        secrets: inherit
    outputs:
      sts4-language-servers-version: ${{ steps.timestamp.outputs.date }}

  e427-distro:
    runs-on: ubuntu-latest
    needs: [ eclipse-ls-extension ]
    steps:
      - uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
        with:
          eclipse_profile: 'e427'
          build_type: 'release'
          p2-qualifier: 'RELEASE'
          sts4-language-servers-version: ${{ needs.eclipse-ls-extension.outputs.sts4-language-servers-version }}

  e428-distro:
    runs-on: ubuntu-latest
    needs: [ eclipse-ls-extension ]
    steps:
      - uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
        with:
          eclipse_profile: 'e428'
          build_type: 'release'
          p2-qualifier: 'RELEASE'
          sts4-language-servers-version: ${{ needs.eclipse-ls-extension.outputs.sts4-language-servers-version }}

  e429-distro:
    runs-on: ubuntu-latest
    needs: [ eclipse-ls-extension ]
    steps:
      - uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
        with:
          eclipse_profile: 'e429'
          build_type: 'release'
          p2-qualifier: 'RELEASE'
          sts4-language-servers-version: ${{ needs.eclipse-ls-extension.outputs.sts4-language-servers-version }}
