name: Snapshot - 4.31 Eclipse STS Distribution Build

concurrency:
  group: e431-snapshot
  cancel-in-progress: true

#on:
#  workflow_dispatch:
on:
  workflow_run:
    workflows: ["Snapshot - Eclipse LS Extensions"]
    types: [completed]
    branches:
      - "main"

jobs:
  e430-distro:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/gh-hosted-eclipse-distro-build.yml
    with:
      eclipse_profile: 'e431'
      build_type: 'snapshot'
    secrets: inherit