name: Test Slack Message

on:
  workflow_dispatch:

jobs:
  slack-message:
    name: Send slack message
    runs-on: ubuntu-latest
    steps:
      - id: slack
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "Test message title `Version` is available now",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Test Message text `Version` is available now"
                  }
                }
              ]
            }
