name: Test Slack Message

on:
  workflow_dispatch:

jobs:
  slack-message:
    name: Send slack message
    runs-on: ubuntu-latest
    steps:
      - id: slack
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117
        env:
          SLACK_BOT_TOKEN: ${{ secrets.VMWARE_SLACK_BOT_TOKEN }}
        with:
          channel-id: "C0188MENU2J"
          payload: |
            {
              "text": "Test message title `Version` is available now",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Test Message text `Version` is available now"
                  }
                }
              ]
            }
