name: Update Aggregate Update Sites

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version suffix in S3
        required: true
        type: string

jobs:

  update-aggregate-update-sites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          sparse-checkout: |
            .github
      - name: Timestamp
        id: timestamp
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Generate and Upload Aggregate Update Sites Data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_S3_SECRET_KEY  }}
          AWS_DEFAULT_REGION: us-east-1
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_CACHE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}
        run: |
          dirs=`aws s3 ls s3://dist.springsource.com/release/TOOLS/sts4/update/${{ inputs.version }}/`
          pattern='^e[0-9]+.[0-9]+/$'
          for dir in $dirs
          do
            if [[ "$dir" =~ $pattern ]]; then
              echo "Found ${dir}"
              site_url="https://download.springsource.com/release/TOOLS/sts4/update/${dir}"
              ${{ github.workspace }}/.github/scripts/generate-composite-site-files.sh ${{ steps.timestamp.outputs.date }} $site_url
              cat ./compositeArtifacts.xml
              cat ./compositeContent.xml
            fi
          done