name: Upload nightly-distributions.html form the Repo to S3

on:
  workflow_dispatch:

jobs:

  upload-nightly-downloads-s3-cache:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          ref: ${{ inputs.ref }}
          sparse-checkout: |
            .github
            eclipse-distribution/common/html
      - name: Upload nightly-distributions.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_S3_SECRET_KEY  }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "Removing old nightly-distributions.html from s3..."
          aws s3 rm s3://dist.springsource.com/snapshot/STS4/nightly-distributions.html
          echo "Uploading new nightly-distributions.html to s3..."
          aws s3 cp ./eclipse-distribution/common/html/nightly-distributions.html s3://dist.springsource.com/snapshot/STS4/nightly-distributions.html --acl public-read --no-progress
      - name: Invalidate S3 Cloudfront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_S3_SECRET_KEY  }}
          AWS_DEFAULT_REGION: us-east-1
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_CACHE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_TOKEN }}
        run: |
          ${{ github.workspace }}/.github/scripts/clear-s3-caches-file.sh snapshot/STS4/nightly-distributions.html
