name: Wipe out temp build artifacts

# configure manual trigger
on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cloudgate S3 Configuration
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          aws-access-key-id:  ${{ secrets.TOOLS_CLOUDGATE_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TOOLS_CLOUDGATE_SECRET_KEY  }}
          role-to-assume: arn:aws:iam::${{ secrets.TOOLS_CLOUDGATE_ACCOUNT_ID }}:role/${{ secrets.TOOLS_CLOUDGATE_USER }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-1
          role-duration-seconds: 900
          role-skip-session-tagging: true
      - name: Remove Temp Build Artifacts from S3
        id: cleanup-s3-temp-storage
        run: |
          aws s3 rm s3://dist.springsource.com/sts4-distro-ci-temp --recursive --exclude "*" --include "*.zip"

